<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Alpha-3HLS322" name="TestCases.TC_cross_Login_logout" tests="5" failures="0" timestamp="2021-04-05T14:35:27 EDT" time="0.011" errors="1">
  <testcase name="lauchtoGooglePage" time="0.011" classname="TestCases.TC_cross_Login_logout">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at TestCases.TC_cross_Login_logout.lauchtoGooglePage(TC_cross_Login_logout.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- lauchtoGooglePage -->
  <system-out/>
  <testcase name="GotoLoginPage" time="0.000" classname="TestCases.TC_cross_Login_logout">
    <skipped/>
  </testcase> <!-- GotoLoginPage -->
  <system-out/>
  <testcase name="Loginto" time="0.000" classname="TestCases.TC_cross_Login_logout">
    <skipped/>
  </testcase> <!-- Loginto -->
  <system-out/>
  <testcase name="Search" time="0.000" classname="TestCases.TC_cross_Login_logout">
    <skipped/>
  </testcase> <!-- Search -->
  <system-out/>
  <testcase name="Logout" time="0.000" classname="TestCases.TC_cross_Login_logout">
    <skipped/>
  </testcase> <!-- Logout -->
  <system-out/>
</testsuite> <!-- TestCases.TC_cross_Login_logout -->
